Philipye314/imp 2 qr code scanner
calblueprint/impact-fund pull request #3
Opened 2023-10-01 23:19 UTC by philipye314

## What's new in this PR

### Description

[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

### Screenshots

[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy!"

## How to review

[//]: # 'Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?'

## Next steps

[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."

## Relevant Links

### Online sources

[//]: # 'Optional - copy links to any tutorials or documentation that was useful to you when working on this PR'

### Related PRs

[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @stephaniewong2

2023-10-10 07:10 UTC, stephaniewong2 requested changes
So good!

2023-10-10 07:10 UTC, stephaniewong2 commented on src/app/(BottomTabNavigation)/Cases/QRCodeScanner/index.tsx
> +import { TouchableOpacity } from 'react-native-gesture-handler';
This is likely my fault but use `TouchableOpacity` from `react-native`, not `react-native-gesture-handler`

2023-10-10 07:10 UTC, stephaniewong2 commented on src/app/(BottomTabNavigation)/Cases/QRCodeScanner/img/crosshair.png
We don't need the crosshair so let's remove this!

2023-10-10 07:10 UTC, stephaniewong2 commented on src/app/(BottomTabNavigation)/Cases/QRCodeScanner/index.tsx
> +        style={[styles.scanner]} // StyleSheet.absoluteFillObject,
Remove comment

2023-10-10 07:10 UTC, stephaniewong2 commented on src/app/(BottomTabNavigation)/Cases/QRCodeScanner/index.tsx
> +      <Image style={styles.crosshair} source={require('./img/crosshair.png')} />
Let's remove the crosshair here. It's misaligned from my end for some reason but we also don't need!

2023-10-10 20:54 UTC, stephaniewong2 commented on src/app/(BottomTabNavigation)/Cases/QRCodeScanner/styles.ts
> +  crosshair: {
Remove after removing crosshair!

2023-10-11 19:47 UTC, stephaniewong2 requested changes
Few minor comments but besides that looks good to me! Don't forget to pull from main because it'll block you from merging!

2023-10-11 19:47 UTC, stephaniewong2 commented on src/screens/QRCodeScanner/QRCodeScanner.tsx
Let's delete this and the `screens` directory

2023-10-11 19:47 UTC, stephaniewong2 commented on src/app/(BottomTabNavigation)/Cases/styles.ts
> +  scanner: {
The `scanner` styles is located in `/src/app/(BottomTabNavigation)/Cases/QRCodeScanner/styles` so let's remove this

2023-10-13 02:34 UTC, stephaniewong2 approved these changes

2023-10-13 02:52 UTC, philipye314 commented
created working barcode scanner

2023-10-13 02:52 UTC, merged