copy pasted previous branch over; there are nav issues?
calblueprint/impact-fund pull request #47
Opened 2023-11-30 02:39 UTC by me-liu

## What's new in this PR

### Description

[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

- screens and nav for name/email/pword and address
- error handling for password
- frontend

### Screenshots

[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy!"

## How to review

[//]: # 'Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?'
- copy pasted from the other signup page

## Next steps

[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."

- the navigation is a little odd, although it looks like it was that way from main? Not sure why though since the nav doesn't seem to have changed. Can't move from the profile -> address in signup and can't see the login page when navigating from the welcome screen. pls help Stephanie ty

## Relevant Links

### Online sources

[//]: # 'Optional - copy links to any tutorials or documentation that was useful to you when working on this PR'

### Related PRs

[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @stephaniewong2

2023-12-02 20:09 UTC, stephaniewong2 requested changes

2023-12-02 20:09 UTC, stephaniewong2 commented on src/app/(Authentication)/SignUp/Address/index.tsx
> +  const [streetAddress, setStreetAddress] = useState('');
Type all `useStates`!!

2023-12-02 20:09 UTC, stephaniewong2 commented on src/app/(Authentication)/SignUp/Address/index.tsx
> +          <TextInput
Let's use Folasade's `MiniAuthInput` for these

2023-12-02 20:09 UTC, stephaniewong2 commented on src/app/(Authentication)/SignUp/Profile/index.tsx
> +  const [name, setName] = useState('');
Type all `useStates`

2024-02-09 07:16 UTC, closed without merging

2024-02-09 07:16 UTC, ronniebeggs commented
Code was copied into a new PR.