Auth Flow Styling Bugs
calblueprint/impact-fund pull request #85
Opened 2024-04-21 06:27 UTC by me-liu

## What's new in this PR
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."
- created an AuthButton, and changed all buttons to that button
- changed some of the wording to match the figma

### Screenshots
- lowkey it looks the same

## How to review
[//]: # 'Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?'

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."

## Relevant Links
### Online sources
[//]: # 'Optional - copy links to any tutorials or documentation that was useful to you when working on this PR'

### Related PRs
[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @ronniebeggs

2024-04-21 18:36 UTC, ronniebeggs requested changes
Looks good so far. A few simplifying changes should be applied across screens to make styling consistent.

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/Welcome/index.tsx
> +          </ButtonBlack>
Login button currently routes to the sign up flow.

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/OTPFlow/OTPVerify/index.tsx
> +              tap here to resend it.
Can we underline this text so it's clear where to press.

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/OTPFlow/OTPVerify/index.tsx
> +          style={styles.nextButtonBase}
The styled component shouldn't have additional styling unless this instance is different from others.

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/OTPFlow/OTPVerify/index.tsx
> +          <Text style={styles.instructionText}>We've sent it to {email}</Text>
Apply a 100% width so it fills the content container and has the same width as the OPT container below.

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/SignUp/Address/index.tsx
> +        style={styles.nextButton}
Remove this redundant style prop

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/SignUp/Address/index.tsx
>          </View>
can we remove the view that wraps the check icon. Instead wrap both the "Sign Up" text and icon with one View container that centers them along the same axis and separates them by a column gap. That way we can remove margins from text components.

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/Welcome/index.tsx
> +          </View>
I'd prefer to use a container with heigh 0 that has a bottom width. That way it expands and shrinks depending on the screen size, whereas an SVG line has the same dimensions regardless. Check the `/Components/EligibilityCard` to see how this is done.

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/Welcome/styles.ts
> +    width: 315,
Can we keep this as a percentage width.

2024-04-21 18:36 UTC, ronniebeggs commented on src/Components/AuthButton/AuthButton.tsx
> +  border-width: 2px;
Border width should be 1px

2024-04-21 18:36 UTC, ronniebeggs commented on src/app/(Authentication)/Login/Email/index.tsx
>        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
Can we add a `contentContainer` View that defines the width of the content on this screen. That way all components have a consistent width.

2024-04-25 02:57 UTC, stephaniewong2 reviewed
remove back button on forgot password flow

2024-05-01 19:53 UTC, merged